parameters:
  cronjob_log_directory: "%kernel.project_dir%/public/Cronjob/"

services:
    _defaults:
      autowire: true
      autoconfigure: true

    FmCronjobManagerBundle\:
      namespace: 'Fm\CronjobManagerBundle\'
      resource: '../src/'
      exclude:
        - '../src/DependencyInjection/'
        - '../src/Kernel.php'